### ISSUE TITLE
How to get SQL query return value?

### ISSUE THREAD

**Issue by wyc8242** [onecrayon/database-webos#1]
var a = this.$.db.getSelect('user','');
only return a.sql(select \* from user), a.values is empty
I promise the table have records,

Looking forward to your reply

thanks.

**Comment by onecrayon** [comment]
Hello,

You are using it incorrectly. All calls are asynchronous, so you need to pass in a function callback to onSuccess, which will receive the results object.

Ian

**Comment by wyc8242** [comment]
I got it.
thanks,
